# Generated by Django 2.2.24 on 2022-10-14 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20221013_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 13, 38, 24, 653039, tzinfo=utc), null=True, verbose_name='когда появился'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 13, 38, 24, 653284, tzinfo=utc), null=True, verbose_name='когда пропал'),
        ),
    ]
