# Generated by Django 2.2.24 on 2022-10-14 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20221014_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 13, 55, 4, 143184, tzinfo=utc), null=True, verbose_name='когда появился'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 14, 13, 55, 4, 143254, tzinfo=utc), null=True, verbose_name='когда пропал'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='pokemon_entities.Pokemon', verbose_name='покемон'),
        ),
    ]
